In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
import joblib
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import roc_auc_score, roc_curve, auc
import matplotlib.pyplot as plt
from sklearn import metrics

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
data = {'Expressions':['He is good', 'I am feeling blessed', 'He achived his goal', 'She is good with technology', 'He is well known person', 
                       'He scored good marks', 'she has a beautiful family', 'he is proud of himself', 'Python is amazing',
                       'Scala has very good time complexity', 'she cooks well', 'They play basketball very nicely', 
                       'He rides the bike perfectly', 'I love python', 'I know maths', 'We wake up early in the morning', 
                       'My brother speaks loudly', 'I have driven a car', 'We are trying to understand',
                       'I am buying a new pair of shoes',
                       'Java is tough', 'he knows how to deal with bad things', 'I am not flying to Europe', 'I do not know scala', 
                       'They are not from gulbarga', 'They do not know how to communicate', 'they are ruthless', 
                       'He does not have to commute to work', 'They do not prectice yoga', 'she will not be watching TV', 
                       'He has not been walking', 'We will not overcome the problems', 'She had not been working', 
                       'He had not been reading a book', 'He will not have received enough score by the summer', 
                       'They had not gone out when you called', 'The woman had not cried till the morning', 
                       'I had not returned to university', 'The rain will not have stopped by tomorrow', 
                       'I will not have been staying in London next summer'], 
        'Category':[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}

In [3]:
df = pd.DataFrame(data)

In [4]:
df

Expressions  Category
0                                          He is good         1
1                                I am feeling blessed         1
2                                 He achived his goal         1
3                         She is good with technology         1
4                             He is well known person         1
5                                He scored good marks         1
6                          she has a beautiful family         1
7                              he is proud of himself         1
8                                   Python is amazing         1
9                 Scala has very good time complexity         1
10                                     she cooks well         1
11                   They play basketball very nicely         1
12                        He rides the bike perfectly         1
13                                      I love python         1
14                                       I know maths         1
15                    We wake up early in the morning         1
16                           My brother speaks loudly         1
17                                I have driven a car         1
18                        We are trying to understand         1
19                    I am buying a new pair of shoes         1
20                                      Java is tough         0
21               he knows how to deal with bad things         0
22                          I am not flying to Europe         0
23                                I do not know scala         0
24                         They are not from gulbarga         0
25                They do not know how to communicate         0
26                                  they are ruthless         0
27                He does not have to commute to work         0
28                          They do not prectice yoga         0
29                        she will not be watching TV         0
30                            He has not been walking         0
31                  We will not overcome the problems         0
32                           She had not been working         0
33                     He had not been reading a book         0
34  He will not have received enough score by the ...         0
35              They had not gone out when you called         0
36           The woman had not cried till the morning         0
37                   I had not returned to university         0
38         The rain will not have stopped by tomorrow         0
39  I will not have been staying in London next su...         0

In [5]:
df.shape

(40, 2)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Expressions  40 non-null     object
 1   Category     40 non-null     int64 
dtypes: int64(1), object(1)
memory usage: 768.0+ bytes


In [7]:
df['Expressions'] = df['Expressions'].str.strip().str.lower()

In [8]:
df

Expressions  Category
0                                          he is good         1
1                                i am feeling blessed         1
2                                 he achived his goal         1
3                         she is good with technology         1
4                             he is well known person         1
5                                he scored good marks         1
6                          she has a beautiful family         1
7                              he is proud of himself         1
8                                   python is amazing         1
9                 scala has very good time complexity         1
10                                     she cooks well         1
11                   they play basketball very nicely         1
12                        he rides the bike perfectly         1
13                                      i love python         1
14                                       i know maths         1
15                    we wake up early in the morning         1
16                           my brother speaks loudly         1
17                                i have driven a car         1
18                        we are trying to understand         1
19                    i am buying a new pair of shoes         1
20                                      java is tough         0
21               he knows how to deal with bad things         0
22                          i am not flying to europe         0
23                                i do not know scala         0
24                         they are not from gulbarga         0
25                they do not know how to communicate         0
26                                  they are ruthless         0
27                he does not have to commute to work         0
28                          they do not prectice yoga         0
29                        she will not be watching tv         0
30                            he has not been walking         0
31                  we will not overcome the problems         0
32                           she had not been working         0
33                     he had not been reading a book         0
34  he will not have received enough score by the ...         0
35              they had not gone out when you called         0
36           the woman had not cried till the morning         0
37                   i had not returned to university         0
38         the rain will not have stopped by tomorrow         0
39  i will not have been staying in london next su...         0

In [9]:
x = df['Expressions']
y = df['Category']

In [10]:
x, x_test, y, y_test = train_test_split(x, y, stratify=y, test_size=0.30, random_state=3)

In [11]:
vec = CountVectorizer(stop_words='english')

In [12]:
x = vec.fit_transform(x).toarray()

In [13]:
x_test = vec.transform(x_test).toarray()

In [14]:
x

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [15]:
y

26    0
13    1
38    0
19    1
24    0
37    0
21    0
8     1
39    0
29    0
31    0
1     1
10    1
27    0
3     1
35    0
5     1
32    0
0     1
34    0
4     1
11    1
6     1
16    1
36    0
7     1
9     1
22    0
Name: Category, dtype: int64

In [16]:
from sklearn.neural_network import MLPClassifier

In [17]:
mlp = MLPClassifier(hidden_layer_sizes=(50, 50))
mlp.fit(x, y)

MLPClassifier(hidden_layer_sizes=(50, 50))

In [18]:
predictions = mlp.predict(x_test)

In [19]:
predictions

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
from sklearn.metrics import confusion_matrix, classification_report

In [21]:
print(confusion_matrix(y_test, predictions))

[[5 1]
 [6 0]]


In [22]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       0.45      0.83      0.59         6
           1       0.00      0.00      0.00         6

    accuracy                           0.42        12
   macro avg       0.23      0.42      0.29        12
weighted avg       0.23      0.42      0.29        12

